### ISSUE TITLE
binary data

### ISSUE THREAD

**Issue by lazydino** [alexstrat/simudp#3]
Hi, is simudp capable of handling binary data? Can I transmit and receive byte array?

**Comment by alexstrat** [comment]
The short answer is "I'm not sure and depends on how you implement it".

The longest answers are:
- you can very probably find a way to stringify/de-stringify your binary data and make it travel through simudp. It might be under-efficient, but it should work.
- `simudup` is based on a browser portage of the `buffer` Node.js module. At the time it was compiled with [browserify](http://browserify.org/), `SimUDP.js` embedded a previous version (but don't know which one) of @toots's portage (https://github.com/toots/buffer-browserify). You should check that this module did support binary data and how.
- it looks like the `buffer` portage in browserify has evolved towards an other [implementation](https://github.com/feross/buffer) with [newer browserify versions](https://github.com/substack/node-browserify/blob/master/changelog.markdown#shiny-new-buffer). Given that this new implementation leverage browser's `Uint8Array`, it might better support binary data. If you feel adventurous, you can try to compile `SimUDP.js` with that new portage and give it a try.
- anyway, `simudup` uses [Buffer#toString](https://github.com/alexstrat/simudp/blob/master/lib/simudp.js#L117), so whatever `buffer` portage is used, if you are looking for efficiency, you might need to tweak that.

**Comment by lazydino** [comment]
Hi, I am re-visiting this repository and try the three lines proxy server provided in ReadMe, but node came back with the following message.

  if(server instanceof sio.Manager)
                          ^
TypeError: Expecting a function in instanceof check, but got #<Server>
    at Object.exports.listen (c:\udptest\node_modules\simudp\lib\server.js:49:27
)
    at Object.<anonymous> (c:\udptest\app.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Can you help? I did not have the right version of socket.io? All I did is just install package via npm and run 
var server = require('http').createServer();

require('simudp').listen(server);

server.listen(8080);

**Comment by alexstrat** [comment]
Arrff.. i'm sorry about that. It's an old module I wrote years ago and that I don't maintain anymore. It is probably very dusty..

I was able to get rid of this issue by commenting the culprit lines in `./lib/server.js`, but haven't investigate further:

``` js
exports.listen = function(server, options) {
  options = options || {};
  var io;

  // if(server instanceof sio.Manager)
  //   io = server;
  // else
    io = sio.listen(server, options['socket.io'] || {});

  new Proxy(io.of('/simudp'), options.port_range, options.whoami);
  //..
```

(I'm running node v0.12.1, I checkouted the repo and ran `npm install .`)

It might work like that, but not sure.

Sorry again.

**Comment by lazydino** [comment]
I just change the socket.io package verion requirement from ">0.9.11" to "^0.9.12", SimUDP will then work with the older socket.io
